food_hacks/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('foods.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
]

urlpatterns+= [

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

foods/urls.py
from . import views
from django.urls import path

app_name = 'foods'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:item_id>/', views.detail, name='detail'),
    path('item/', views.item, name='item'),

    path('add',views.create_item,name='create_item'),
path('delete/<int:id>/',views.delete_item,name='delete_item'),

    path('update/<int:id>/', views.update_item, name='update_item'),
    path('aboutus/',views.aboutus,name='aboutus'),
]

foods/models.py
from django.db import models

# Create your models here.

class Item(models.Model):
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_calorie = models.IntegerField()
    item_image = models.CharField(max_length=500,default ="https://cdn.dribbble.com/users/1012566/screenshots/4187820/topic-2.jpg?compress=1&resize=800x600")

    def __str__(self):
        return self.item_name

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

foods/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_calorie','item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

foods/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
from django.template import loader,Context


# Create your views here.

def index(request):
     item_list =Item.objects.all()

     context = {
       'item_list': item_list,
     }
     return render(request,'foods/index.html',context)

def item(request):
    return HttpResponse("<h1>i am a view</h1>")

def detail(request,item_id):
     item = Item.objects.get(pk=item_id)
     context = {
         'item': item,
     }
     return render(request,'foods/detail.html',context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('foods:index')

    return render(request,'foods/item-form.html',{'form':form})

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None,instance=item)

    if form.is_valid():
        form.save()
        return redirect('foods:index')
    return render(request,'foods/item-form.html',{'form':form,'item':item})


def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('foods:index')
    return render(request,'foods/item-delete.html',{'item':item})

def aboutus(request):

        template = loader.get_template('foods/aboutus.html')
        return HttpResponse(template.render)

users/views.py
from django.shortcuts import render,redirect

from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required




# Create your views here.

def register(request):
    if request.method== 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is created')
            return redirect('login')
    else:
         form = RegisterForm()
    return render(request,'users/register.html',{'form': form})


def profilepage(request):
    return render(request,'users/profile.html')

foods/templates/foods/aboutus.html
{% extends 'foods/base.html' %}

{% block body %}
<body>

{{ item.item_name }}
</body>


{% endblock %}

foods/templates/foods/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'foods/style.css' %}">
</head>
<body>


<nav class="navbar navbar-dark bg-dark">

    <a href="#" class="navbar-brand">FoodApp</a>

    <div class="navbar">
        <a class="nav-item nav-link " href="{% url 'foods:index' %}">FoodDetails</a>
        <a class="nav-item nav-link" href="{% url 'foods:create_item' %}">Add Details</a>


        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
        <a href ="{% url 'profile' %}">Profile</a>
         {% else %}
        <a href="{% url 'login' %}">Login</a>
        {% endif %}


    </div>

</nav>

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
{{ message }}
</div>
{% endfor %}
{% endif %}
  {% block body %}
{% endblock %}
</body>
</html>

foods/templates/foods/detail.html
{% extends 'foods/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height="320px" src="{{ item.item_image }}" class="card"/>
        </div>
        <div class="col-md-6">
            <h2> {{ item.item_name }}</h2> <br>
            <h4> {{ item.item_desc }} </h4><br>
            <h4>{{  item.item_calorie }}</h4>
            <a href="{% url 'foods:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

foods/templates/foods/index.html
{% extends 'foods/base.html' %}
<html>

<head>

</head>
<body>

{% block body %}
{% for item in item_list %}
  <div class="row">
      <div class="col-md-3 offset-md-2">
          <img class="card" height="150px" src="{{ item.item_image}}">

      </div>
      <div class="col-md-4">
          <h3>{{ item.item_name }}</h3>
           <h5>{{ item.item_desc }}</h5>
          <h5>Calorie per dish -> {{ item.item_calorie }}</h5>

      </div>
      <div class="col-md-2">
        <a href="{% url 'foods:detail' item.id %}" class="btn btn-success">Check out details!</a>
      </div>
  </div>


{% endfor %}
{% endblock %}

</body>


</html>

foods/templates/foods/item-delete.html
{% extends 'foods/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add item
                    </div>
                </div>
                <div class="card-body">
                 <form method="POST">
  {% csrf_token %}
  <h2>Are you sure u want to delete??</h2>
  <button type="Submit">Confirm</button>
</form>

                </div>
            </div>
        </div>
    </div>

</div>


{%  endblock %}

<form method="POST">
  {% csrf_token %}
  <h2>Are you sure u want to delete??</h2>
  <button type="Submit">Confirm</button>
</form>

foods/templates/foods/item-form.html
{% extends 'foods/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add item
                    </div>
                </div>
                <div class="card-body">
                 <form method="POST">
                  {% csrf_token %}

                     {% for field in form  %}
              <div class="form-group">
                  {{ field.name }}
                  {{ field }}
                  {% endfor %}
              </div>
  <button type="Submit">Save</button>
</form>
                </div>
            </div>
        </div>
    </div>

</div>


{%  endblock %}

users/templates/users/login.html
{% extends 'foods/base.html' %}
{% block body %}



<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add item
                    </div>
                </div>
                <div class="card-body">
                  <form method="POST">
          {% csrf_token %}
             {% for field in form  %}
              <div class="form-group">
                  {{ field.name }}
                  {{ field }}
              </div>
             {% endfor %}
          <button class="btn-info" type="Submit"> Login </button>
          </form>
                </div>
            </div>
        </div>
    </div>

</div>



{% endblock %}

users/templates/users/logout.html
<h1>You have been logged out</h1>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src="{{ user.profile}}"/>

users/templates/users/register.html
{% extends 'foods/base.html' %}

{% block body %}



<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add item
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
  {% csrf_token %}
  {{ form }}
  <button type="Submit">Sign Up</button>
</form>
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock %}